### PR TITLE
Added button styling to home page

### PR DESCRIPTION
**Pull request by dexterquiambao**
Screenshot 2020-11-17 at 23 38 33
Screenshot 2020-11-17 at 23 39 06

1)Fixed quick styling on buttons - buttons are reusable for other pages with slight hover animation
--> styling located in components > _buttons.scss

2) Removed extra text that was in between the banner and navbar

### CODE REVIEW

**Review by alfiehiscox — APPROVED** [review]
Good job!

**Comment by l-sturgeon** [comment]
Looking good!

**Comment by dexterquiambao** [comment]
Added dynamic random pictures of castles and changed the font to "Lora"

**Review by alfiehiscox — COMMENTED** [review]
Looks great

**Pull request merged**
